### ISSUE TITLE
Revolutbot.py still usable ? 

### ISSUE THREAD

**Issue by VictorJ76** [tducret/revolut-python#27]
Hello, 
I was trying to use the revolut bot but got python errors : 

```
01:/opt/revolut-python# revolutbot.py --historyfile=exchange_history.csv --device-id=XXXXXXXXXXXX --token=XXXXXXXXXXXXXXXXXXXXXXXX
Traceback (most recent call last):
  File "/usr/local/bin/revolutbot.py", line 140, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/revolutbot.py", line 70, in main
    forceexchange=forceexchange)
  File "/usr/local/bin/revolutbot.py", line 82, in to_buy_or_not_to_buy
    filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/revolut_bot/__init__.py", line 69, in get_last_transactions_from_csv
    return list(map(dict_transaction_to_Transaction, last_transactions))
  File "/usr/local/lib/python3.6/dist-packages/revolut_bot/__init__.py", line 80, in dict_transaction_to_Transaction
    real_amount=float(tr_dict["from_amount"]),
TypeError: float() argument must be a string or a number, not 'NoneType'
```

I don't know where to check first. any help ?

**Comment by VictorJ76** [comment]
Ok, My history transaction file was not correct. I close this useless issue. 
Futhermore, does any documentation for revolutbot will come in the next weeks ?
