### ISSUE TITLE
Status code 401 : The request should be authorized

### ISSUE THREAD

**Issue by VictorJ76** [tducret/revolut-python#30]
Hello, 

Since a few days, I got a 401 from api.revolut.com. I tried to regenerate a new token but even with one I still got a 401.
Does the issue is on my side or revolut ?

```
root@01:/opt/revolut-python# python3 revolutbot.py --historyfile=/opt/revolut-python/exchange_history.csv --token==  --verbose --simulate 
Last transaction : (05/10/2020 16:30:00) X EUR => X BTC
Traceback (most recent call last):
  File "revolutbot.py", line 140, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "revolutbot.py", line 67, in main
    to_buy_or_not_to_buy(revolut=rev,
  File "revolutbot.py", line 90, in to_buy_or_not_to_buy
    current_balance_in_other_currency = revolut.quote(
  File "/opt/revolut-python/revolut/__init__.py", line 221, in quote
    ret = self.client._get(url_quote)
  File "/opt/revolut-python/revolut/__init__.py", line 148, in _get
    raise ConnectionError(
ConnectionError: Status code 401 for url https://api.revolut.com/quote/BTCEUR?amount=XX&side=SELL
{"message":"The request should be authorized."}
```

**Comment by VictorJ76** [comment]
Generated a token a third time and solved my issue

**Comment by InfiniteScope** [comment]
Can we reopen it, I have the same problem!!
