### ISSUE TITLE
cannot generate token

### ISSUE THREAD

**Issue by AntouanK** [tducret/revolut-python#7]
Hi.

Thanks for your work.

I tried the pip module and the source code, both cases the same issue.
See below:

```
styx :: ~/_REPOS_/revolut-python » ./revolut_cli.py 
You don't seem to have a Revolut token
Would you like to generate a token [yes/no] ? yes
What is your mobile phone (used with your Revolut account) [ex : +33612345678] ? +44**********
What is your Revolut app password [ex: 1234] ? ****
Traceback (most recent call last):
  File "./revolut_cli.py", line 90, in <module>
    main()
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./revolut_cli.py", line 42, in main
    get_token()
  File "./revolut_cli.py", line 65, in get_token
    password=password,
  File "/run/media/antouank/evo1/_REPOS_/revolut-python/revolut/__init__.py", line 337, in get_token_step1
    expected_status_code=204)
TypeError: _post() got an unexpected keyword argument 'json'

```

**Comment by tducret** [comment]
My bad. We did some cleanup in the latest version... and I made a mistake.
You can install the previous version :
pip3 install revolut==0.0.6

**Comment by AntouanK** [comment]
I tried installing 0.0.6

```
styx :: ~/_REPOS_/revolut-python 1 » pip install --user revolut==0.0.6
Collecting revolut==0.0.6
  Downloading https://files.pythonhosted.org/packages/b6/b6/7ceae238b5330205c40c6793bd408e8b29cdd407350b3b0153a106c3f2c1/revolut-0.0.6.tar.gz
Requirement already satisfied: requests>=2.6.0 in /usr/lib/python3.7/site-packages (from revolut==0.0.6) (2.22.0)
Requirement already satisfied: click>=6.7 in /home/antouank/.local/lib/python3.7/site-packages (from revolut==0.0.6) (7.0)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.7/site-packages (from requests>=2.6.0->revolut==0.0.6) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.7/site-packages (from requests>=2.6.0->revolut==0.0.6) (2.8)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.7/site-packages (from requests>=2.6.0->revolut==0.0.6) (1.25.3)
Building wheels for collected packages: revolut
  Building wheel for revolut (setup.py) ... done
  Stored in directory: /home/antouank/.cache/pip/wheels/bf/47/5f/f92264437205bded1840bb512c0390ab21372707a063da838e
Successfully built revolut
Installing collected packages: revolut
  Found existing installation: revolut 0.0.7
    Uninstalling revolut-0.0.7:
      Successfully uninstalled revolut-0.0.7
Successfully installed revolut-0.0.6
```

I get a different error now

```
styx :: ~/_REPOS_/revolut-python » revolut_cli.py
You don't seem to have a Revolut token
Would you like to generate a token [yes/no] ? yes
What is your mobile phone (used with your Revolut account) [ex : +33612345678] ? +44*********
What is your Revolut app password [ex : 1234] ? ****
Traceback (most recent call last):
  File "/home/antouank/.local/bin/revolut_cli.py", line 88, in <module>
    main()
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/antouank/.local/bin/revolut_cli.py", line 41, in main
    get_token()
  File "/home/antouank/.local/bin/revolut_cli.py", line 62, in get_token
    password=password)
  File "/home/antouank/.local/lib/python3.7/site-packages/revolut/__init__.py", line 330, in get_token_step1
    expected_status_code=204)
  File "/home/antouank/.local/lib/python3.7/site-packages/revolut/__init__.py", line 149, in _post
    status=ret.status_code, url=url, content=ret.text))
ConnectionError: Status code 401 for url https://api.revolut.com/signin
```

**Comment by tducret** [comment]
That is different. 401 status code means Unauthorized, meaning either code
you supplied is wrong or that the Revolut API changed.
It needs a bit more investigation.

**Comment by AntouanK** [comment]
Any idea how we can find out what's wrong?

**Comment by tducret** [comment]
Hi @AntouanK. I released version `0.0.8`to fix the first problem.
Can you test it after upgrade (`pip3 install -U revolut`)

**Comment by AntouanK** [comment]
@tducret Thanks for working on this.

Still seems to have some issue though :(

```
➜  ~ revolut_cli.py 
You don't seem to have a Revolut token
Would you like to generate a token [yes/no] ? yes
What is your mobile phone (used with your Revolut account) [ex : +33612345678] ? +PHONE_NUMBER
What is your Revolut app password [ex: 1234] ? 
Traceback (most recent call last):
  File "/home/antouank/.local/bin/revolut_cli.py", line 91, in <module>
    main()
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/antouank/.local/bin/revolut_cli.py", line 43, in main
    get_token()
  File "/home/antouank/.local/bin/revolut_cli.py", line 66, in get_token
    password=password,
  File "/home/antouank/.local/lib/python3.7/site-packages/revolut/__init__.py", line 337, in get_token_step1
    expected_status_code=204)
  File "/home/antouank/.local/lib/python3.7/site-packages/revolut/__init__.py", line 150, in _post
    status=ret.status_code, url=url, content=ret.text))
ConnectionError: Status code 400 for url https://api.revolut.com/signin
{"message":"Required 'app version' is missing"}
```

**Comment by tducret** [comment]
Found it @AntouanK !
A new key is now needed in the header. I fixed it.
Please update to `0.0.9` with `pip install revolut -U`

**Comment by AntouanK** [comment]
```
styx :: ~ » revolut_cli.py                    
You don't seem to have a Revolut token
Would you like to generate a token [yes/no] ? yes
What is your mobile phone (used with your Revolut account) [ex : +33612345678] ? +44***********
What is your Revolut app password [ex: 1234] ? 
Traceback (most recent call last):
  File "/home/antouank/.local/bin/revolut_cli.py", line 91, in <module>
    main()
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/antouank/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/antouank/.local/bin/revolut_cli.py", line 43, in main
    get_token()
  File "/home/antouank/.local/bin/revolut_cli.py", line 66, in get_token
    password=password,
  File "/home/antouank/.local/lib/python3.7/site-packages/revolut/__init__.py", line 338, in get_token_step1
    expected_status_code=200)
  File "/home/antouank/.local/lib/python3.7/site-packages/revolut/__init__.py", line 151, in _post
    status=ret.status_code, url=url, content=ret.text))
ConnectionError: Status code 401 for url https://api.revolut.com/signin

styx :: ~ 1 » revolut_cli.py --version
revolut_cli.py, based on [revolut] package version 0.0.9
```

**Comment by tducret** [comment]
That is weird. Could you make sure that your Revolut app password is correct please?
Check that it is the same as the password entered on the official app.

**Comment by AntouanK** [comment]
the password is the 4-digit pin, right?

**Comment by tducret** [comment]
Yes

**Comment by AntouanK** [comment]
my bad, mistyped the phone number.


do I have to log out from the app first?
It says I got an SMS but I don't get one. I just get an app notification and no code.

**Comment by tducret** [comment]
Yes, good idea to logout since the app must intercept the SMS before it is readable.

**Comment by leikoilja** [comment]
@tducret, mayne it's worth mentioning that you should logout from the app in `README`? Was not receiving SMS from Revolut before I saw that discussion and logged out :+1:

**Comment by tducret** [comment]
👍 Just did it in 71eb9f5 @leikoilja
